version: '2.2'

services:
  core:
    volumes:
    - share-volume:/opt/jumpserver/apps/xpack
    depends_on:
      - xpack
  celery:
    volumes:
      - share-volume:/opt/jumpserver/apps/xpack
    depends_on:
      - xpack
  xpack:
    image: registry.fit2cloud.com/jumpserver/xpack:${VERSION}
    container_name: jms_xpack
    restart: always
    volumes:
      - share-volume:/opt/xpack
    healthcheck:
      test: "ls -d /opt/xpack/"
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - net

volumes:
  share-volume:
