version: '2.4'

services:
  core:
    image: ${REGISTRY:-docker.io}/jumpserver/core-ce:${VERSION}
    container_name: jms_core
    hostname: jms_core
    tty: true
    command: sleep
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/core/config.yml:/opt/jumpserver/config.yml
      - ${CONFIG_DIR}/certs:/opt/jumpserver/data/certs
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net
