version: '2.2'

services:
  lb:
    image: jumpserver/nginx:alpine2
    container_name: jms_lb
    restart: always
    env_file:
      - /opt/jumpserver/config/config.txt
    ports:
      - ${LB_HTTP_PORT}:80
      - ${LB_HTTPS_PORT}:443
      - ${LB_SSH_PORT}:2222
    volumes:
      - ${VOLUME_DIR}/lb/log:/var/log/nginx
      - /opt/jumpserver/config/nginx/cert:/etc/nginx/cert
      - /opt/jumpserver/config/nginx/lb_http_server.conf:/etc/nginx/conf.d/default.conf
      - /opt/jumpserver/config/nginx/lb_ssh_server.conf:/etc/nginx/stream.d/ssh_server.conf
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - net