version: '2.2'

services:
  core:
    volumes:
    - share-volume:/opt/jumpserver/apps/xpack
    depends_on:
      - xpack
  celery:
    volumes:
      - share-volume:/opt/jumpserver/apps/xpack
    depends_on:
      - xpack
  xpack:
    image: jumpserver/xpack:${VERSION}
    container_name: jms_xpack
    volumes:
      - share-volume:/opt/xpack
    networks:
      - net

volumes:
  share-volume: