version: '2.4'

services:
  core:
    image: registry.fit2cloud.com/jumpserver/core:${VERSION}

  celery:
    image: registry.fit2cloud.com/jumpserver/core:${VERSION}

  koko:
    image: registry.fit2cloud.com/jumpserver/koko:${VERSION}

  lion:
    image: registry.fit2cloud.com/jumpserver/lion:${VERSION}

  magnus:
    image: registry.fit2cloud.com/jumpserver/magnus:${VERSION}
    ports:
      - ${MAGNUS_POSTGRESQL_PORT:-54320}:54320
      - ${MAGNUS_ORACLE_PORTS:-30000-30030}:${MAGNUS_ORACLE_PORTS:-30000-30030}
  chen:
    image: registry.fit2cloud.com/jumpserver/chen:${VERSION}

  web:
    image: registry.fit2cloud.com/jumpserver/web:${VERSION}

  razor:
    image: registry.fit2cloud.com/jumpserver/razor:${VERSION}
    container_name: jms_razor
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - ${CONFIG_FILE}
    ports:
      - ${RDP_PORT}:3389
    volumes:
      - ${VOLUME_DIR}/razor/data:/opt/razor/data
      - ${CONFIG_DIR}/nginx/cert:/opt/razor/cert
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "ps axu | grep -v 'grep' | grep 'razor'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
