services:
  redis:
    image: swaprepo.apk-group.net/apkpam/strv1/module/redis:7.0-bullseye
    container_name: jms_redis
    hostname: jms_redis
    restart: always
    command: ["redis-server", "/etc/redis.conf", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      TZ: ${TZ:-Asia/Tehran}
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    volumes:
      - ${VOLUME_DIR}/redis/data:/data
      - ${CONFIG_DIR}/redis/redis.conf:/etc/redis.conf
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p $$REDIS_PORT -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
